<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="basetest"
           tests="3"
           failures="1"
           errors="0"
           skipped="2"
           time="3.238">
    <properties></properties>

            <testcase
                name="setUp"
                time="3.238"
                classname="tests.Test_Latihan2">

            <failure type="java.lang.NullPointerException" message="Cannot invoke &quot;Utility.Data.getUrlHrm()&quot; because &quot;this.setup&quot; is null">
                <![CDATA[java.lang.NullPointerException: Cannot invoke "Utility.Data.getUrlHrm()" because "this.setup" is null
                tests.BaseTest.setUp(BaseTest.java:55)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:568)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)java.base/java.util.ArrayList.forEach(ArrayList.java:1511)org.testng.TestRunner.privateRun(TestRunner.java:808)org.testng.TestRunner.run(TestRunner.java:603)org.testng.SuiteRunner.runTest(SuiteRunner.java:429)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)org.testng.SuiteRunner.run(SuiteRunner.java:326)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)org.testng.TestNG.runSuitesLocally(TestNG.java:1169)org.testng.TestNG.runSuites(TestNG.java:1092)org.testng.TestNG.run(TestNG.java:1060)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>

            <testcase
                name="getResult"
                time="0.0"
                classname="tests.Test_Latihan2">
            </testcase>
            <testcase
                name="clickAdd"
                time="0.0"
                classname="tests.Test_Latihan2">
            </testcase>

</testsuite>
